spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:test}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}
    driverClassName: com.mysql.jdbc.Driver
  flyway:
    baselineOnMigrate: true
    user: ${DB_MIGRATION_USER:root}
    password: ${DB_MIGRATION_PASSWORD:}
  jpa:
    database: MYSQL
#    hibernate:
#      #      ddl-auto: none
#      ddl-auto: validate
#    #      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQL57Dialect
#        jdbc:
#          batch_size: 100
